info:
  build:
    version: 0.0.1
  name: founderNest

# Local
spring:
  config:
    name: founderNest

server:
  undertow:
    accesslog:
      enabled: true
      dir: target/logs
      pattern: combined
  compression:
    enabled: true
    min-response-size: 1

swagger:
  externalHostName: localhost:8080